type Quote = { price: number; change: number; changePct: number; volume: number; high: number; low: number };
type Bar = { date: string; open: number; high: number; low: number; close: number; volume: number };
const base = "https://api.coingecko.com/api/v3";
async function get(path: string) { const res = await fetch(`${base}${path}`); if (!res.ok) throw new Error(`CoinGecko request failed (${res.status})`); return res.json(); }
function toQuote(id: string, value: Record<string, number>): Quote { return { price: value.usd, change: value.usd_24h_change ? value.usd * value.usd_24h_change / (100 + value.usd_24h_change) : 0, changePct: value.usd_24h_change ?? 0, volume: value.usd_24h_vol ?? 0, high: value.usd, low: value.usd }; }
export async function fetchQuotesBatch(ids: string[]): Promise<Record<string, Quote>> { const data = await get(`/simple/price?ids=${encodeURIComponent(ids.join(","))}&vs_currencies=usd&include_24hr_change=true&include_24hr_vol=true`) as Record<string, Record<string, number>>; return Object.fromEntries(Object.entries(data).map(([id, value]) => [id, toQuote(id, value)])); }
export async function fetchQuote(id: string) { const quotes = await fetchQuotesBatch([id]); if (!quotes[id]) throw new Error(`No quote found for ${id}`); return quotes[id]; }
export async function searchSymbols(query: string) { const data = await get(`/search?query=${encodeURIComponent(query)}`) as { coins?: { id: string; name: string; symbol: string }[] }; return (data.coins ?? []).slice(0, 10).map((coin) => ({ symbol: coin.id, name: `${coin.name} (${coin.symbol.toUpperCase()})` })); }
export async function fetchDailySeries(id: string, days: number): Promise<Bar[]> { const data = await get(`/coins/${encodeURIComponent(id)}/market_chart?vs_currency=usd&days=${days}`) as { prices: [number, number][]; total_volumes: [number, number][] }; return data.prices.map(([timestamp, close], index) => { const volume = data.total_volumes[index]?.[1] ?? 0; return { date: new Date(timestamp).toISOString().slice(0, 10), open: close, high: close, low: close, close, volume }; }); }
